import Head from "next/head";

import { Inter } from "next/font/google";

import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import ProjectSection from "@/components/ProjectSection";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Shopity Developer Clone</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main id="main" className="bg-dark-900">
				<Navbar />
				<Hero />
				<ProjectSection />
				<Footer />
			</main>
		</>
	);
}
